### ISSUE TITLE
/browser-sync/socket.io/

### ISSUE THREAD

**Issue by lifeiscontent** [rails-api/rails-api#189]
Why when I create a new rails-api app why does this request happen and how to do I fix it?

``` sh
cuevent-api $ rails s
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-02-22 11:21:50] INFO  WEBrick 1.3.1
[2015-02-22 11:21:50] INFO  ruby 2.1.3 (2014-09-19) [x86_64-darwin13.0]
[2015-02-22 11:21:50] INFO  WEBrick::HTTPServer#start: pid=38910 port=3000


Started GET "/browser-sync/socket.io/?EIO=3&transport=polling&t=1424632913344-65" for ::1 at 2015-02-22 11:21:53 -0800

ActionController::RoutingError (No route matches [GET] "/browser-sync/socket.io"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /Users/lifeiscontent/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/lifeiscontent/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/lifeiscontent/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


  Rendered /Users/lifeiscontent/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered /Users/lifeiscontent/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/routes/_table.html.erb (5.0ms)
  Rendered /Users/lifeiscontent/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /Users/lifeiscontent/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (17.7ms)
```

**Comment by steveklabnik** [comment]
We don't make any requests, this is something your application is doing. Can you post some sort of reproduction?

**Comment by lifeiscontent** [comment]
@steveklabnik you're right, I had a tab open that was hitting this endpoint from browser-sync. I'm sorry for wasting your time!

**Comment by buncis** [comment]
> @steveklabnik you're right, I had a tab open that was hitting this endpoint from browser-sync. I'm sorry for wasting your time!

not so wasted dude you help me debug this XD
