### ISSUE TITLE
rails-api new failed cause of `undefined local variable or method 'app_secret'`

### ISSUE THREAD

**Issue by Anudorannador** [rails-api/rails-api#227]
- RUBY INFO:

```
ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
gem list rails

*** LOCAL GEMS ***
coffee-rails (4.2.2)
rails (5.2.1)
rails-api (0.4.1)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.4)
sass-rails (5.0.7)
sprockets-rails (3.2.1)
```

LOGS:

```bash
rails-api new sexyrobot
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/anudorannador/Desktop/sexyrobot/.git/
      create  package.json
      create  app
      create  app/controllers/application_controller.rb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/filter_parameter_logging.rb
Traceback (most recent call last):
	48: from /usr/local/bin/rails-api:23:in `<main>'
	47: from /usr/local/bin/rails-api:23:in `load'
	46: from /var/lib/gems/2.5.0/gems/rails-api-0.4.1/bin/rails-api:4:in `<top (required)>'
	45: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	44: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	43: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/cli.rb:18:in `<top (required)>'
	42: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
	41: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
	40: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	39: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	38: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	37: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands/application/application_command.rb:26:in `perform'
	36: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	35: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	34: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	33: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	32: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	31: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	30: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	29: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	28: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/generators/rails/app/app_generator.rb:314:in `create_config_files'
	27: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/generators/app_base.rb:159:in `build'
	26: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/generators/rails/app/app_generator.rb:110:in `config'
	25: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/generators/rails/app/app_generator.rb:19:in `inside'
	24: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions.rb:186:in `inside'
	23: from /var/lib/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:124:in `cd'
	22: from /var/lib/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:124:in `chdir'
	21: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions.rb:186:in `block in inside'
	20: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/generators/rails/app/app_generator.rb:120:in `block in config'
	19: from /var/lib/gems/2.5.0/gems/railties-5.2.1/lib/rails/generators/rails/app/app_generator.rb:19:in `directory'
	18: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/directory.rb:52:in `directory'
	17: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions.rb:94:in `action'
	16: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/directory.rb:66:in `invoke!'
	15: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/directory.rb:80:in `execute!'
	14: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/directory.rb:80:in `each'
	13: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/directory.rb:92:in `block in execute!'
	12: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:119:in `template'
	11: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:25:in `create_file'
	10: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions.rb:94:in `action'
	 9: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:60:in `invoke!'
	 8: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
	 7: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:63:in `block in invoke!'
	 6: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:63:in `open'
	 5: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
	 4: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:53:in `render'
	 3: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:122:in `block in template'
	 2: from /usr/lib/ruby/2.5.0/erb.rb:876:in `result'
	 1: from /usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
/var/lib/gems/2.5.0/gems/rails-api-0.4.1/lib/rails-api/templates/rails/app/config/initializers/secret_token.rb.tt:19:in `template': undefined local variable or method `app_secret' for #<Rails::Generators::AppGenerator:0x00005574ed29a9e8> (NameError)
Did you mean?  app_const
```

OTHER:
My system is Ubuntu 18.04 and install ruby by command `sudo apt install ruby gem`

**Comment by rafaelfranca** [comment]
Rails API is not needed anymore in Rails 5.2. You can remove it.

**Comment by felix91gr** [comment]
Wait, wait! I have the exact same problem. How should I create an API from Rails now that the gem is part of Rails itself? I'm a noob to Rails (more or less), sorry if I'm asking something obvious :see_no_evil:

**Comment by icbd** [comment]
should use `rails new app_name --api`
